### ISSUE TITLE
Unexpected change in YOLOv8 output format

### ISSUE THREAD

**Issue by Ludvig-Joborn** [vladiH/flutter_vision#26]
Hi!

I used this package earlier this summer, and it worked just fine!
But ever since, any YOLOv8 model I try to export using Ultralytics exports will give an output format that is unrecognizable to the program as it previously was. The most recent updates to this package don't seem to make a difference, unfortunately.

Any ideas as to why this might be occurring, or how to address the issue? Let me know if you need more info for debuggin!

Example previous output (working):
[[1587.7335205078125, 693.9750366210938, 1921.768798828125, 1119.3153076171875, 0.9181058406829834], tag: obj}, 
{box: [2221.90576171875, 754.1986694335938, 2613.1064453125, 1153.677001953125, 0.3026130199432373], tag: obj}, 
{box: [2323.805419921875, 1268.9488525390625, 2681.66845703125, 1696.794677734375, 0.9503433704376221], tag: obj}, 
{box: [1531.5927734375, 1640.84130859375, 2018.4903564453125, 1948.836669921875, 0.6532635688781738], tag: obj}]

Example new output (broken):
[[1.239598274230957, 0.5401819348335266, 1.4939693212509155, 0.8794116377830505, 0.9612507224082947], tag: obj}, 
{box: [1.7374616861343384, 0.588816225528717, 2.0423240661621094, 0.9065394401550293, 0.9636867642402649], tag: obj}, 
{box: [1.8174190521240234, 0.9895595908164978, 2.099705457687378, 1.3236058950424194, 0.965178370475769], tag: obj}, 
{box: [1.195393681526184, 1.2803641557693481, 1.5751936435699463, 1.5251888036727905, 0.969660222530365], tag: obj}]

**Comment by vladiH** [comment]
Hi @Ludvig-Joborn,

Thank you for reaching out to me and bringing this issue to my attention. You are absolutely correct; this problem arose because YoloV8 is currently unstable. They have recently modified the output format, and I've already made the necessary fixes. However, I'm currently deliberating on how to release the new version.

I'm mindful of the fact that some users are still using the previous version, and making a deliberate change in the delivery process may result in inconveniences for them.

**Comment by vladiH** [comment]
@Ludvig-Joborn New version [1.1.4](https://pub.dev/packages/flutter_vision/versions/1.1.4) released
