### ISSUE TITLE
in last update 1.1.4

### ISSUE THREAD

**Issue by maheralzoubi97** [vladiH/flutter_vision#29]
All readings from the model are the same

[{box: [720.0, 1280.0, 720.0, 1280.0, 0.5922492742538452], tag: 5}

**Comment by vladiH** [comment]
Hi @maheralzoubi97,
Could you please provide more details and which  model you are using? It would be really helpful in diagnosing and addressing the issue. Thank you!

**Comment by maheralzoubi97** [comment]
Hi I used
YOLO8
All readings received from the model

Similar
I tried version 1.1.1 and this problem did not occur

**Comment by vladiH** [comment]
This issue likely are happening because you are using an older version of Yolo8. Flutter_vision 1.1.4 was aligned with the new release of [ultralytics](https://github.com/ultralytics/ultralytics). You might want to try version 1.1.3, which should work ok. Please give it a try and let me know if the issue persists.
